### ISSUE TITLE
nxlog connection refused error

### ISSUE THREAD

**Issue by airhack87** [unfetter-analytic/unfetter#10]
I have the victim machine and the analytic machine set up. The container is running fine and I can open Kibana console locally on the linux box. Also verified the linux box is listening on 3515, 3516 and 3517.
But the victim machine is not sending log. In the nxlog.log file The error logged is "No connection could be made because the target machine actively refused it"

What could be the issue ?

**Comment by airhack87** [comment]
Turned out to be the VM networking issue. Its solved!!

**Comment by infosec-alchemist** [comment]
Thanks.  The VM has been problematic with connections.  We hoped that having Vagrant scripts would help. But really, the best thing is if we could wrap up and distribute a windows VM.  But we can't.

Glad it is working.  let us know if you have more issues.

**Comment by airhack87** [comment]
The Vagrant script brought up the windows machine but for some reason the victim was unable to communicate with the unfetter linux box over the private network connection.
So fired up a new machine installed nxlog and sysmon with bridged networking and it worked correctly.
A couple of questions.
When a alert is triggered how can i view it through kibana ?
Is is also pushed to a log ?
Can the unfetter discover app be run on the same linux box as the unfetter analytics. I tried running it but when I create a new Assessment the page is stuck on loading.
I have read the alerts is also sent to the unfetter discover app, where in the app is it shown.

**Comment by infosec-alchemist** [comment]
So, we have a couple of problems.  When we built this, the kibana dashboards started right up, the Unfetter Discover Webapp started right up, and the data was flowing. There was code that you could run on the windows system that would do a process injection and you could see the results. 

However, Elastico changed their installation locations and broke everything.  I recently have been trying to reconstitute with new versions.  if you checked it out recently, it will build the ELK stack in the version 5.x.  It will run the analytics.  

An easy thing to do is to go to your windows box and clear the System log.  That will show up as an alert.  The alert is an ELK document of index CAR_* and alias'ed to "alert".  I haven't had the chance to build the new kibana dashboards, though.  

Also, the webapp doesn't build automatically because we made some changes to the webapp and I need to fix the code.  The Unfetter Analytic project isn't as well maintained as our Unfetter Discover, so I'm behind on it.

**Comment by airhack87** [comment]
Thanks for the index name, I got the index pattern in kibana and created a dashboard got more than a few alerts as i had metasploit, empire and other malware fired up on the victim
This is a really nice way to integrate  MITRE'S CAR and malware IOCs for analytics and testing.
I see an index by the  sitaware, what exactly is that ?

**Comment by infosec-alchemist** [comment]
The CAR analytics have analytic "type".  Some, like Situational Awareness doesn't really denote an actual event, but something to watch.  There was thought that having a couple of SITAWARE indexed analytics together might be an event.  I likely should take out sitware all together since it is really splitting hairs with only a few analytics in the system.

Glad you like it.  Feel free to do a pull request with your kibana dashboards if you like.
